title : 'sound server'
default_name : 'default'
file_type : 'mp3'
saykana : '/usr/local/bin/saykana'
ffmpeg : '/usr/local/bin/ffmpeg'

mongo :
  server : '127.0.0.1'
  port : 27017
  dbname : 'sound-server'
